[package]
name = "phoenixentertainment/playerdatasystem-client"
description = "Handles the loading, saving & schema migration of player save-data."
version = "3.0.0-rc.1"
authors = ["Noble_Draconian"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
DragonEngine = "nobledraconian/dragon-engine@2.0.0"
roblox-libmodules = "nobledraconian/roblox-libmodules@3.1.0"
Table = "sleitnick/table-util@1.2.1"
