[package]
name = "phoenixentertainment/playerdatasystem-client"
description = "Player data system client"
version = "2.1.0"
authors = ["Noble_Draconian"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
DragonEngine = "nobledraconian/dragon-engine@2.0.0"
roblox-libmodules = "nobledraconian/roblox-libmodules@3.1.0"