[tools]
rojo = "rojo-rbx/rojo@7.2.1"
selene = "Kampfkarren/selene@0.22.0"
remodel = "rojo-rbx/remodel@0.11.0"
mantle = "blake-mealey/mantle@0.11.6"
wally = "upliftgames/wally@0.3.1"
lune = "filiptibell/lune@0.4.0"