[package]
name = "phoenixentertainment/playerdatasystem-server"
description = "Player data system server"
version = "2.0.0"
authors = ["Noble_Draconian"]
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
DragonEngine = "nobledraconian/dragon-engine@2.0.0"
roblox-libmodules = "nobledraconian/roblox-libmodules@3.1.0"