name : Publish system packages to registry
on:
  release:
    types: [published]

jobs:
  package-publish:
    uses: PhoenixEntertainment/Package-CI/.github/workflows/PackagePublish.yml@master
    secrets: inherit