name : System Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create system release
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: PhoenixEntertainment/Package-CI/.github/workflows/PackageRelease@master